# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e17765d15cfd8c4288142015774568500b3cf31dd8019e5975e24d092ef299e91e6cf696129728ba28b1484f9de31f4d93eb5e1ba760be3d977934ef826847be

test:
  secret_key_base: 2cab259e5186e5266e8ed69d1e865c8fb14998962fb333b5cf6afd4271acd0e6a6153748aff8f5c6979323770009a191641b039df151ae6bf74ed04a4055047c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
